
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      .NET Framework 向け Microsoft (R) Build Engine バージョン 16.11.2+f32259642
      Copyright (C) Microsoft Corporation.All rights reserved.
      
      2024/04/11 11:08:03 にビルドを開始しました。
      ノード 1 上のプロジェクト "C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\3.29.1\\CompilerIdC\\CompilerIdC.vcxproj" (既定のターゲット)。
      PrepareForBuild:
        ディレクトリ "Debug\\" を作成しています。
        ディレクトリ "Debug\\CompilerIdC.tlog\\" を作成しています。
      InitializeBuildStatus:
        "AlwaysCreate" が指定されたため "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" を作成しています。
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\3.29.1\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        ファイル "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" を削除しています。
        "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate" のタッチ タスクを実行しています。
      プロジェクト "C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\3.29.1\\CompilerIdC\\CompilerIdC.vcxproj" (既定のターゲット) のビルドが完了しました。
      
      ビルドに成功しました。
          0 個の警告
          0 エラー
      
      経過時間 00:00:00.51
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/shuushi/ihspp_lib-master/ihspp_lib-master/build/CMakeFiles/3.29.1/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      .NET Framework 向け Microsoft (R) Build Engine バージョン 16.11.2+f32259642
      Copyright (C) Microsoft Corporation.All rights reserved.
      
      2024/04/11 11:08:03 にビルドを開始しました。
      ノード 1 上のプロジェクト "C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\3.29.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (既定のターゲット)。
      PrepareForBuild:
        ディレクトリ "Debug\\" を作成しています。
        ディレクトリ "Debug\\CompilerIdCXX.tlog\\" を作成しています。
      InitializeBuildStatus:
        "AlwaysCreate" が指定されたため "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" を作成しています。
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc142.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\3.29.1\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        ファイル "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" を削除しています。
        "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate" のタッチ タスクを実行しています。
      プロジェクト "C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\3.29.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (既定のターゲット) のビルドが完了しました。
      
      ビルドに成功しました。
          0 個の警告
          0 エラー
      
      経過時間 00:00:00.33
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/shuushi/ihspp_lib-master/ihspp_lib-master/build/CMakeFiles/3.29.1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/shuushi/ihspp_lib-master/ihspp_lib-master/build/CMakeFiles/CMakeScratch/TryCompile-r3lfal"
      binary: "C:/shuushi/ihspp_lib-master/ihspp_lib-master/build/CMakeFiles/CMakeScratch/TryCompile-r3lfal"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/shuushi/ihspp_lib-master/ihspp_lib-master/build/CMakeFiles/CMakeScratch/TryCompile-r3lfal'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe" cmTC_d2eaf.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        .NET Framework 向け Microsoft (R) Build Engine バージョン 16.11.2+f32259642
        Copyright (C) Microsoft Corporation.All rights reserved.
        
        2024/04/11 11:08:04 にビルドを開始しました。
        ノード 1 上のプロジェクト "C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\CMakeScratch\\TryCompile-r3lfal\\cmTC_d2eaf.vcxproj" (既定のターゲット)。
        PrepareForBuild:
          ディレクトリ "cmTC_d2eaf.dir\\Debug\\" を作成しています。
          ディレクトリ "C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\CMakeScratch\\TryCompile-r3lfal\\Debug\\" を作成しています。
          ディレクトリ "cmTC_d2eaf.dir\\Debug\\cmTC_d2eaf.tlog\\" を作成しています。
        InitializeBuildStatus:
          "AlwaysCreate" が指定されたため "cmTC_d2eaf.dir\\Debug\\cmTC_d2eaf.tlog\\unsuccessfulbuild" を作成しています。
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d2eaf.dir\\Debug\\\\" /Fd"cmTC_d2eaf.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.29\\Modules\\CMakeCCompilerABI.c"
          Microsoft(R) C/C++ Optimizing Compiler Version 19.29.30154 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d2eaf.dir\\Debug\\\\" /Fd"cmTC_d2eaf.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.29\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\CMakeScratch\\TryCompile-r3lfal\\Debug\\cmTC_d2eaf.exe" /INCREMENTAL /ILK:"cmTC_d2eaf.dir\\Debug\\cmTC_d2eaf.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/shuushi/ihspp_lib-master/ihspp_lib-master/build/CMakeFiles/CMakeScratch/TryCompile-r3lfal/Debug/cmTC_d2eaf.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/shuushi/ihspp_lib-master/ihspp_lib-master/build/CMakeFiles/CMakeScratch/TryCompile-r3lfal/Debug/cmTC_d2eaf.lib" /MACHINE:X64  /machine:x64 cmTC_d2eaf.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_d2eaf.vcxproj -> C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\CMakeScratch\\TryCompile-r3lfal\\Debug\\cmTC_d2eaf.exe
        FinalizeBuildStatus:
          ファイル "cmTC_d2eaf.dir\\Debug\\cmTC_d2eaf.tlog\\unsuccessfulbuild" を削除しています。
          "cmTC_d2eaf.dir\\Debug\\cmTC_d2eaf.tlog\\cmTC_d2eaf.lastbuildstate" のタッチ タスクを実行しています。
        プロジェクト "C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\CMakeScratch\\TryCompile-r3lfal\\cmTC_d2eaf.vcxproj" (既定のターゲット) のビルドが完了しました。
        
        ビルドに成功しました。
            0 個の警告
            0 エラー
        
        経過時間 00:00:00.32
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:170 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'C': C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:207 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the C compiler's linker: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.29.30154.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/shuushi/ihspp_lib-master/ihspp_lib-master/build/CMakeFiles/CMakeScratch/TryCompile-j2tg2u"
      binary: "C:/shuushi/ihspp_lib-master/ihspp_lib-master/build/CMakeFiles/CMakeScratch/TryCompile-j2tg2u"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/shuushi/ihspp_lib-master/ihspp_lib-master/build/CMakeFiles/CMakeScratch/TryCompile-j2tg2u'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe" cmTC_479d3.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:n
        .NET Framework 向け Microsoft (R) Build Engine バージョン 16.11.2+f32259642
        Copyright (C) Microsoft Corporation.All rights reserved.
        
        2024/04/11 11:08:04 にビルドを開始しました。
        ノード 1 上のプロジェクト "C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\CMakeScratch\\TryCompile-j2tg2u\\cmTC_479d3.vcxproj" (既定のターゲット)。
        PrepareForBuild:
          ディレクトリ "cmTC_479d3.dir\\Debug\\" を作成しています。
          ディレクトリ "C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\CMakeScratch\\TryCompile-j2tg2u\\Debug\\" を作成しています。
          ディレクトリ "cmTC_479d3.dir\\Debug\\cmTC_479d3.tlog\\" を作成しています。
        InitializeBuildStatus:
          "AlwaysCreate" が指定されたため "cmTC_479d3.dir\\Debug\\cmTC_479d3.tlog\\unsuccessfulbuild" を作成しています。
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_479d3.dir\\Debug\\\\" /Fd"cmTC_479d3.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.29\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft(R) C/C++ Optimizing Compiler Version 19.29.30154 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_479d3.dir\\Debug\\\\" /Fd"cmTC_479d3.dir\\Debug\\vc142.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.29\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\CMakeScratch\\TryCompile-j2tg2u\\Debug\\cmTC_479d3.exe" /INCREMENTAL /ILK:"cmTC_479d3.dir\\Debug\\cmTC_479d3.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/shuushi/ihspp_lib-master/ihspp_lib-master/build/CMakeFiles/CMakeScratch/TryCompile-j2tg2u/Debug/cmTC_479d3.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/shuushi/ihspp_lib-master/ihspp_lib-master/build/CMakeFiles/CMakeScratch/TryCompile-j2tg2u/Debug/cmTC_479d3.lib" /MACHINE:X64  /machine:x64 cmTC_479d3.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_479d3.vcxproj -> C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\CMakeScratch\\TryCompile-j2tg2u\\Debug\\cmTC_479d3.exe
        FinalizeBuildStatus:
          ファイル "cmTC_479d3.dir\\Debug\\cmTC_479d3.tlog\\unsuccessfulbuild" を削除しています。
          "cmTC_479d3.dir\\Debug\\cmTC_479d3.tlog\\cmTC_479d3.lastbuildstate" のタッチ タスクを実行しています。
        プロジェクト "C:\\shuushi\\ihspp_lib-master\\ihspp_lib-master\\build\\CMakeFiles\\CMakeScratch\\TryCompile-j2tg2u\\cmTC_479d3.vcxproj" (既定のターゲット) のビルドが完了しました。
        
        ビルドに成功しました。
            0 個の警告
            0 エラー
        
        経過時間 00:00:00.32
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:170 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:207 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the CXX compiler's linker: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.29.30154.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
